// fetch campaign list
export const FETCH_CAMPAIGN_START = "FETCH_CAMPAIGN_START";
export const FETCH_CAMPAIGN_SUCCESS = "FETCH_CAMPAIGN_SUCCESS";
export const FETCH_CAMPAIGN_FAILED = "FETCH_CAMPAIGN_FAILED";

// create campaign
export const CREATE_CAMPAIGN_START = "CREATE_CAMPAIGN_START";
export const CREATE_CAMPAIGN_SUCCESS = "CREATE_CAMPAIGN_SUCCESS";
export const CREATE_CAMPAIGN_FAILED = "CREATE_CAMPAIGN_FAILED";

// delete campaign
export const DELETE_CAMPAIGN_START = "DELETE_CAMPAIGN_START";
export const DELETE_CAMPAIGN_SUCCESS = "DELETE_CAMPAIGN_SUCCESS";
export const DELETE_CAMPAIGN_FAILED = "DELETE_CAMPAIGN_FAILED";

// update campaign
export const UPDATE_CAMPAIGN_START = "UPDATE_CAMPAIGN_START";
export const UPDATE_CAMPAIGN_SUCCESS = "UPDATE_CAMPAIGN_SUCCESS";
export const UPDATE_CAMPAIGN_FAILED = "UPDATE_CAMPAIGN_FAILED";
